name: Tests Python
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      run: pip3 install -r requirements.txt
    - name: Run Python
      env: 
          coinmarketcap: ${{ secrets.COINMARKETCAP }}
      run: python3 CoinIDScrapper.py
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: data.json
