name: Tests Swift
on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: xcodebuild test -scheme CoinIdSwift -project CoinIdSwift/CoinIdSwift.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' | xcpretty && exit ${PIPESTATUS[0]}
